const products = [
    // Electronics (1-10)
    {
        id: 1,
        title: "Smart Watch - Series 7",
        itemType: "Smart Watch",
        description: "Advanced smart watch with health monitoring and always-on retina display",
        category: "electronics",
        price: 1099,
        brand: "Apple",
        rating: 4.8,
        stock: 50,
        image: "https://rukminim2.flixcart.com/image/850/1000/xif0q/smartwatch/g/e/0/1-99-android-ios-t800-ultra-smartwatch-wireless-charging-original-imagz2kzpu8xsggr.jpeg?q=90&crop=false"
    },
    {
        id: 2,
        title: "Wireless Bluetooth Earbuds",
        itemType: "Wireless Earbuds",
        description: "True wireless earbuds with active noise cancellation and 24hr battery",
        category: "electronics",
        price: 1499,
        brand: "Sony",
        rating: 4.5,
        stock: 75,
        image: "https://m.media-amazon.com/images/I/51pycg0MGxL.jpg"
    },
    {
        id: 3,
        title: "LED Ring Light with Tripod",
        itemType: "Ring Light",
        description: "18-inch adjustable ring light with 3 color temperatures and smartphone holder",
        category: "electronics",
        price: 899,
        brand: "Godox",
        rating: 4.3,
        stock: 40,
        image: "https://www.izicart.com/cdn/shop/files/ring-light-n.webp?v=1745061853&width=416"
    },
    {
        id: 4,
        title: "Mi 40 inch Smart LED TV",
        itemType: "Smart TV",
        description: "Full HD Android TV with Dolby Audio and PatchWall",
        category: "electronics",
        price: 15999,
        brand: "Xiaomi",
        rating: 4.4,
        stock: 15,
        image: "https://rukminim2.flixcart.com/image/850/1000/k9u8zgw0/television/g/5/r/mi-l40m5-5ain-original-imafrjtbrjazqtgr.jpeg?q=90&crop=false"
    },
    {
        id: 5,
        title: "Portable Bluetooth Speaker",
        itemType: "Bluetooth Speaker",
        description: "Waterproof speaker with 20hr playtime and deep bass",
        category: "electronics",
        price: 1299,
        brand: "JBL",
        rating: 4.6,
        stock: 60,
        image: "https://www.boat-lifestyle.com/cdn/shop/files/Stone_SpinXPro_1.png?v=1709717404"
    },
    {
        id: 6,
        title: "Smart Home Security Camera",
        itemType: "Security Camera",
        description: "1080p indoor camera with motion detection and night vision",
        category: "electronics",
        price: 2499,
        brand: "TP-Link",
        rating: 4.2,
        stock: 30,
        image: "https://assets.airtel.in/static-assets/b2c-surveillance/images/products_2/listing/active-def@2x.png"
    },
    {
        id: 7,
        title: "Gaming Headset",
        itemType: "Headphones",
        description: "Surround sound gaming headset with noise-cancelling mic",
        category: "electronics",
        price: 1799,
        brand: "Razer",
        rating: 4.7,
        stock: 45,
        image: "https://m.media-amazon.com/images/I/61CGHv6kmWL._SL1500_.jpg"
    },
    {
        id: 8,
        title: "Wireless Charging Pad",
        itemType: "Charger",
        description: "15W fast wireless charging pad compatible with Qi-enabled devices",
        category: "electronics",
        price: 999,
        brand: "Samsung",
        rating: 4.1,
        stock: 80,
        image: "https://m.media-amazon.com/images/I/61oIAKY9s1L.jpg"
    },
    {
        id: 9,
        title: "Power Bank 20000mAh",
        itemType: "Power Bank",
        description: "High capacity power bank with 18W PD fast charging",
        category: "electronics",
        price: 1899,
        brand: "Anker",
        rating: 4.5,
        stock: 55,
        image: "https://media-ik.croma.com/prod/https://media.croma.com/image/upload/v1725624590/275990_0_nj9tzm.png"
    },
    {
        id: 10,
        title: "Digital Alarm Clock",
        itemType: "Alarm Clock",
        description: "LED digital clock with temperature display and USB charger",
        category: "electronics",
        price: 799,
        brand: "Philips",
        rating: 4.0,
        stock: 65,
        image: "https://rukminim2.flixcart.com/image/850/1000/l1tmf0w0/table-clock/h/u/l/smart-7-color-change-digital-led-alarm-clock-for-office-bedroom-original-imagdazwj83ybkdy.jpeg?q=90&crop=false"
    },

    // Laptops (11-20)
    {
        id: 11,
        title: "HP 15s Ryzen 5 Laptop",
        itemType: "Laptop",
        description: "15.6-inch laptop with AMD Ryzen 5 processor and 8GB RAM",
        category: "laptops",
        price: 39999,
        brand: "HP",
        rating: 4.3,
        stock: 20,
        image: "https://m.media-amazon.com/images/I/71S8U9VzLTL._SL1500_.jpg"
    },
    {
        id: 12,
        title: "Dell Inspiron Core i5 Laptop",
        itemType: "Laptop",
        description: "14-inch FHD laptop with 11th Gen Intel Core i5 processor",
        category: "laptops",
        price: 42999,
        brand: "Dell",
        rating: 4.4,
        stock: 18,
        image: "https://rukminim2.flixcart.com/image/850/1000/kctf0cw0/computer/c/p/j/dell-original-imaftuvzhnqyqafk.jpeg?q=90&crop=false"
    },
    {
        id: 13,
        title: "MacBook Air M1",
        itemType: "Laptop",
        description: "13.3-inch Retina display with Apple M1 chip and 256GB SSD",
        category: "laptops",
        price: 84999,
        brand: "Apple",
        rating: 4.9,
        stock: 12,
        image: "https://cdn.mos.cms.futurecdn.net/MUVBUjdhSRhWxspNxPmLER-1200-80.jpg"
    },
    {
        id: 14,
        title: "Lenovo IdeaPad Slim 5",
        itemType: "Laptop",
        description: "15.6-inch IPS display with AMD Ryzen 7 and 16GB RAM",
        category: "laptops",
        price: 46999,
        brand: "Lenovo",
        rating: 4.5,
        stock: 15,
        image: "https://p1-ofp.static.pub//fes/cms/2025/03/07/kiunzwl13t0bljp3f6bt8kpl58h1xg814997.png"
    },
    {
        id: 15,
        title: "Acer Aspire 7 Gaming Laptop",
        itemType: "Laptop",
        description: "15.6-inch gaming laptop with GTX 1650 and 144Hz display",
        category: "laptops",
        price: 59999,
        brand: "Acer",
        rating: 4.6,
        stock: 10,
        image: "https://lsmedia.linker-cdn.net/266980/2022/7193863.jpeg?d=400x400"
    },
    {
        id: 16,
        title: "Asus VivoBook 14",
        itemType: "Laptop",
        description: "14-inch FHD laptop with Intel Core i3 and fingerprint sensor",
        category: "laptops",
        price: 39999,
        brand: "Asus",
        rating: 4.2,
        stock: 22,
        image: "https://dlcdnwebimgs.asus.com/files/media/71311dd4-7d8a-4b2a-a48e-91b24f456f7c/v3/features/images/large/1x/s4/main.jpg"
    },
    {
        id: 17,
        title: "Microsoft Surface Laptop",
        itemType: "Laptop",
        description: "13.5-inch PixelSense touchscreen with 11th Gen Intel Core",
        category: "laptops",
        price: 74999,
        brand: "Microsoft",
        rating: 4.7,
        stock: 8,
        image: "https://m.media-amazon.com/images/I/510uTHyDqGL._AC_UF1000,1000_QL80_.jpg"
    },
    {
        id: 18,
        title: "HP Pavilion x360",
        itemType: "2-in-1 Laptop",
        description: "14-inch convertible laptop with touchscreen and stylus support",
        category: "laptops",
        price: 54999,
        brand: "HP",
        rating: 4.4,
        stock: 14,
        image: "https://hpstorerajkot.com/wp-content/uploads/CaptureUKLU8KLU9.jpg"
    },
    {
        id: 19,
        title: "Razer Blade 15",
        itemType: "Gaming Laptop",
        description: "15.6-inch QHD 240Hz display with RTX 3070 Ti and i7 processor",
        category: "laptops",
        price: 125999,
        brand: "Razer",
        rating: 4.8,
        stock: 5,
        image: "https://m.media-amazon.com/images/I/71kcJxMggRL._AC_UF1000,1000_QL80_.jpg"
    },
    {
        id: 20,
        title: "Samsung Galaxy Book 3",
        itemType: "Laptop",
        description: "15.6-inch AMOLED touchscreen with S Pen and 13th Gen Intel Core",
        category: "laptops",
        price: 69999,
        brand: "Samsung",
        rating: 4.5,
        stock: 12,
        image: "https://images.samsung.com/is/image/samsung/p6pim/in/feature/164360731/in-feature-galaxy-book3-360-13-3-inch-with-s-pen-np730-535677264?$FB_TYPE_A_MO_JPG$"
    },

    // Smartphones (21-30)
    {
        id: 21,
        title: "iPhone 14 Pro Max",
        itemType: "Smartphone",
        description: "6.7-inch Super Retina XDR display with ProMotion and Dynamic Island",
        category: "smartphones",
        price: 129999,
        brand: "Apple",
        rating: 4.9,
        stock: 15,
        image: "https://m.media-amazon.com/images/I/71yzJoE7WlL._AC_UF1000,1000_QL80_.jpg"
    },
    {
        id: 22,
        title: "Samsung Galaxy S23 Ultra",
        itemType: "Smartphone",
        description: "6.8-inch Dynamic AMOLED 2X with 200MP camera and S Pen support",
        category: "smartphones",
        price: 124999,
        brand: "Samsung",
        rating: 4.8,
        stock: 18,
        image: "https://images-cdn.ubuy.co.in/64d74c749a0e143358699e6b-open-box-samsung-galaxy-s23-ultra-5g.jpg"
    },
    {
        id: 23,
        title: "OnePlus 11 5G",
        itemType: "Smartphone",
        description: "6.7-inch Fluid AMOLED with Hasselblad camera and 100W fast charging",
        category: "smartphones",
        price: 64999,
        brand: "OnePlus",
        rating: 4.7,
        stock: 25,
        image: "https://media-ik.croma.com/prod/https://media.croma.com/image/upload/v1708670974/Croma%20Assets/Communication/Mobiles/Images/268761_0_ptnhsb.png"
    },
    {
        id: 24,
        title: "Google Pixel 7 Pro",
        itemType: "Smartphone",
        description: "6.7-inch LTPO OLED with Google Tensor G2 and 5x optical zoom",
        category: "smartphones",
        price: 79999,
        brand: "Google",
        rating: 4.6,
        stock: 20,
        image: "https://m.media-amazon.com/images/I/61CB-MZkbYL.jpg"
    },
    {
        id: 25,
        title: "Xiaomi Mi 12",
        itemType: "Smartphone",
        description: "6.28-inch AMOLED with Snapdragon 8 Gen 1 and 50MP triple camera",
        category: "smartphones",
        price: 59999,
        brand: "Xiaomi",
        rating: 4.4,
        stock: 30,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTNNWDWT346IKSkN5uJz_qwWE5bRB_PoXTwng&s"
    },
    {
        id: 26,
        title: "Realme GT 2 Pro",
        itemType: "Smartphone",
        description: "6.7-inch LTPO AMOLED with Snapdragon 8 Gen 1 and 150° ultra-wide camera",
        category: "smartphones",
        price: 55999,
        brand: "Realme",
        rating: 4.3,
        stock: 35,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCRRxNQy1gBXLxNUsU4S2dibD5T7BvI_CHSw&s"
    },
    {
        id: 27,
        title: "Oppo Reno 8 Pro",
        itemType: "Smartphone",
        description: "6.7-inch AMOLED with MariSilicon X NPU and 50MP IMX766 sensor",
        category: "smartphones",
        price: 45999,
        brand: "Oppo",
        rating: 4.2,
        stock: 40,
        image: "https://m.media-amazon.com/images/I/51gpYkwfWhL.jpg"
    },
    {
        id: 28,
        title: "Vivo X80",
        itemType: "Smartphone",
        description: "6.78-inch AMOLED with MediaTek Dimensity 9000 and ZEISS optics",
        category: "smartphones",
        price: 56999,
        brand: "Vivo",
        rating: 4.5,
        stock: 28,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRl0ABaNjpMDz5z2igZbmCctPH81aJ9AfB4NQ&s"
    },
    {
        id: 29,
        title: "Nothing Phone 1",
        itemType: "Smartphone",
        description: "6.55-inch OLED with Glyph Interface and dual 50MP cameras",
        category: "smartphones",
        price: 37999,
        brand: "Nothing",
        rating: 4.1,
        stock: 50,
        image: "https://cdn.shopify.com/s/files/1/0514/8554/0505/files/BA_ABR_310_1057.png?v=1661861424"
    },
    {
        id: 30,
        title: "Motorola Edge 30",
        itemType: "Smartphone",
        description: "6.5-inch pOLED with 144Hz refresh rate and Snapdragon 778G+",
        category: "smartphones",
        price: 34999,
        brand: "Motorola",
        rating: 4.0,
        stock: 45,
        image: "https://m.media-amazon.com/images/I/71-jllRLkpL._AC_UF894,1000_QL80_.jpg"
    },

    // Fashion (31-40)
    {
        id: 31,
        title: "Cotton T-shirt for Men",
        itemType: "T-shirt",
        description: "Premium quality cotton t-shirt with regular fit",
        category: "fashion",
        price: 299,
        brand: "Puma",
        rating: 4.2,
        stock: 100,
        image: "https://www.hancockfashion.com/cdn/shop/files/51be7b6a-f0a5-4c53-9635-adccb17be6b31714126302364-Hancock-Men-Solid-Pique-Polo-Collar-Bio-Finish-Pure-Cotton-T-1.jpg?v=1734411563"
        ,
        gender: 'men'
    },
    {
        id: 32,
        title: "Men's Casual Sneakers",
        itemType: "Shoes",
        description: "Lightweight sneakers with cushioned sole and breathable upper",
        category: "fashion",
        price: 799,
        brand: "Adidas",
        rating: 4.3,
        stock: 80,
        image: "https://www.walkaroo.in/cdn/shop/files/3_f646b851-1711-4ffc-b90a-4ffd4ea0ee9c.jpg?v=1740585322",
        gender: 'men'
    },
    {
        id: 33,
        title: "Women's Denim Jacket",
        itemType: "Jacket",
        description: "Classic denim jacket with button closure and multiple pockets",
        category: "fashion",
        price: 1599,
        brand: "Levi's",
        rating: 4.5,
        stock: 45,
        image: "https://www.alamodelabel.in/cdn/shop/files/AD15F82B-CAD5-4B7A-9B2E-814B092A3068_600x600_crop_center.jpg?v=1735462116"
        ,
        gender: 'women'
    },
    {
        id: 34,
        title: "Leather Wallet",
        itemType: "Wallet",
        description: "Genuine leather wallet with multiple card slots and ID window",
        category: "fashion",
        price: 999,
        brand: "Tommy Hilfiger",
        rating: 4.4,
        stock: 60,
        image: "https://imagescdn.peterengland.com/img/app/product/3/39708534-14583048.jpg?auto=format&w=390"
        ,
        gender: 'women'
    },
    {
        id: 35,
        title: "Sports Watch",
        itemType: "Watch",
        description: "Digital sports watch with heart rate monitor and step counter",
        category: "fashion",
        price: 1199,
        brand: "Casio",
        rating: 4.1,
        stock: 70,
        image: "https://m.media-amazon.com/images/I/619ssEP-g6L._AC_UY1000_.jpg"
        ,
        gender: 'unisex'
    },
    {
        id: 36,
        title: "Men's Formal Shoes",
        itemType: "Shoes",
        description: "Premium leather formal shoes with cushioned insole",
        category: "fashion",
        price: 1799,
        brand: "Bata",
        rating: 4.6,
        stock: 40,
        image: "https://assets.ajio.com/medias/sys_master/root/20240125/s47H/65b264cd16fd2c6e6ac1b004/-473Wx593H-467012308-black-MODEL.jpg"
        ,
        gender: 'men'
    },
    {
        id: 37,
        title: "Winter Hoodie",
        itemType: "Hoodie",
        description: "Fleece-lined hoodie with kangaroo pocket and adjustable drawstring",
        category: "fashion",
        price: 1399,
        brand: "Nike",
        rating: 4.3,
        stock: 55,
        image: "https://www.triumph-sports.com/wp-content/uploads/2024/04/Hod37-1.jpg"
        ,
        gender: 'men'
    },
    {
        id: 38,
        title: "Casual Sunglasses",
        itemType: "Sunglasses",
        description: "UV protection sunglasses with polarized lenses and lightweight frame",
        category: "fashion",
        price: 899,
        brand: "Ray-Ban",
        rating: 4.7,
        stock: 90,
        image: "https://d3995ea24pmi7m.cloudfront.net/media/catalog/product/M/8/M8021GY16V_1_lar.jpg"
        ,
        gender: 'men'
    },
    {
        id: 39,
        title: "Stylish Backpack",
        itemType: "Bag",
        description: "Water-resistant backpack with laptop compartment and USB charging port",
        category: "fashion",
        price: 1499,
        brand: "American Tourister",
        rating: 4.5,
        stock: 50,
        image: "https://m.media-amazon.com/images/I/51C-vc8aFnL._AC_UY1100_.jpg"
        ,
        gender: 'unisex'
    },
    {
        id: 40,
        title: "Elegant Wristwatch",
        itemType: "Watch",
        description: "Analog watch with stainless steel case and date display",
        category: "fashion",
        price: 2599,
        brand: "Titan",
        rating: 4.8,
        stock: 35,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTqRr73fFSvPEk6WWgp1T_qjwM_aQw-I7NaUg&s"
        ,
        gender: 'men'
    },

    // Furniture (41-50)
    {
        id: 41,
        title: "Wooden Dining Table",
        itemType: "Dining Table",
        description: "6-seater solid wood dining table with rustic finish",
        category: "furniture",
        price: 15999,
        brand: "HomeTown",
        rating: 4.4,
        stock: 8,
        image: "https://m.media-amazon.com/images/I/91H82-mQZLL.jpg"
    },
    {
        id: 42,
        title: "Recliner Sofa",
        itemType: "Sofa",
        description: "3-seater premium leather recliner sofa with cup holders",
        category: "furniture",
        price: 29999,
        brand: "Durian",
        rating: 4.6,
        stock: 5,
        image: "https://m.media-amazon.com/images/I/51gaCREgf3L.jpg"
    },
    {
        id: 43,
        title: "Office Chair",
        itemType: "Chair",
        description: "Ergonomic office chair with lumbar support and adjustable height",
        category: "furniture",
        price: 5999,
        brand: "Green Soul",
        rating: 4.3,
        stock: 15,
        image: "https://m.media-amazon.com/images/I/71m901lXArL.jpg"
    },
    {
        id: 44,
        title: "Bookshelf Organizer",
        itemType: "Bookshelf",
        description: "5-tier wooden bookshelf with adjustable shelves",
        category: "furniture",
        price: 4999,
        brand: "Nilkamal",
        rating: 4.2,
        stock: 12,
        image: "https://m.media-amazon.com/images/I/81f+tPHylbL._AC_UF894,1000_QL80_.jpg"
    },
    {
        id: 45,
        title: "Coffee Table",
        itemType: "Table",
        description: "Modern glass top coffee table with wooden legs",
        category: "furniture",
        price: 6999,
        brand: "Urban Ladder",
        rating: 4.5,
        stock: 10,
        image: "https://ik.imagekit.io/2xkwa8s1i/img/coffee-tables/praline/1.jpg?tr=w-1200"
    },
    {
        id: 46,
        title: "Bedside Table",
        itemType: "Nightstand",
        description: "Compact bedside table with drawer and open shelf",
        category: "furniture",
        price: 2999,
        brand: "Wakefit",
        rating: 4.1,
        stock: 20,
        image: "https://m.media-amazon.com/images/I/71P9LWMjlDL.jpg"
    },
    {
        id: 47,
        title: "Study Desk",
        itemType: "Desk",
        description: "Study table with bookshelf and CPU stand",
        category: "furniture",
        price: 7999,
        brand: "Spacewood",
        rating: 4.4,
        stock: 14,
        image: "https://m.media-amazon.com/images/I/71fNfkZiUIL.jpg"
    },
    {
        id: 48,
        title: "Shoe Rack",
        itemType: "Storage",
        description: "6-tier shoe organizer with open shelves",
        category: "furniture",
        price: 2499,
        brand: "Amber",
        rating: 4.0,
        stock: 25,
        image: "https://images.woodenstreet.de/image/cache/data/shoe-rack/amantra-sheesham-wood-cane-shoe-rack/walnut-finish/new-logo/2-810x702.jpg"
    },
    {
        id: 49,
        title: "Modular Wardrobe",
        itemType: "Wardrobe",
        description: "Sliding door wardrobe with mirror and multiple compartments",
        category: "furniture",
        price: 19999,
        brand: "Godrej Interio",
        rating: 4.7,
        stock: 6,
        image: "https://5.imimg.com/data5/SELLER/Default/2024/5/417183702/YF/GX/PZ/198776362/modular-wardrobe-500x500.jpg"
    },
    {
        id: 50,
        title: "Outdoor Patio Set",
        itemType: "Furniture Set",
        description: "4-piece outdoor furniture set with table and chairs",
        category: "furniture",
        price: 21999,
        brand: "Fabindia",
        rating: 4.5,
        stock: 4,
        image: "https://sundaydesign.co.in/cdn/shop/files/AlfrescoGrey.jpg?v=1698083400&width=1946"
    },


    // smart watch
    {
        id: 101,
        title: "Noise ColorFit Pro 4",
        itemType: "Smart Watch",
        description: "1.78\" AMOLED display, Bluetooth calling, 60 sports modes",
        category: "electronics",
        price: 2999,
        brand: "Noise",
        rating: 4.3,
        stock: 45,
        image: "https://m.media-amazon.com/images/I/61jOliJK5CL.jpg"
    },
    {
        id: 102,
        title: "Fire-Boltt Ninja 3",
        itemType: "Smart Watch",
        description: "1.69\" display, SpO2 monitor, 24/7 heart rate tracking",
        category: "electronics",
        price: 1799,
        brand: "Fire-Boltt",
        rating: 4.2,
        stock: 60,
        image: "https://rukminim3.flixcart.com/image/850/1000/xif0q/smartwatch/8/a/c/46-48-bsw030-android-ios-fire-boltt-no-original-imagyetdftfxknae.jpeg?q=20&crop=false"
    },
    {
        id: 103,
        title: "Samsung Galaxy Watch 4",
        itemType: "Smart Watch",
        description: "Bioactive sensor, ECG monitoring, Wear OS powered",
        category: "electronics",
        price: 14990,
        brand: "Samsung",
        rating: 4.6,
        stock: 25,
        image: "https://images.samsung.com/is/image/samsung/p6pim/in/2108/gallery/in-galaxy-watch4-398879-sm-r870nzgainu-481111378?$684_547_PNG$"
    },
    {
        id: 104,
        title: "Amazfit GTS 2 Mini",
        itemType: "Smart Watch",
        description: "1.55\" AMOLED display, 14-day battery, 70+ sports modes",
        category: "electronics",
        price: 5999,
        brand: "Amazfit",
        rating: 4.4,
        stock: 30,
        image: "https://in.amazfit.com/cdn/shop/products/2mini_2.jpg?v=1701611944"
    },
    {
        id: 105,
        title: "Realme Watch 3 Pro",
        itemType: "Smart Watch",
        description: "1.78\" AMOLED, Bluetooth calling, 110+ sports modes",
        category: "electronics",
        price: 4499,
        brand: "Realme",
        rating: 4.1,
        stock: 40,
        image: "https://dailydeals365.in/wp-content/uploads/2024/01/realme-Watch-3-Pro-Black-1.webp"
    },
    {
        id: 106,
        title: "Fitbit Versa 3",
        itemType: "Smart Watch",
        description: "GPS, SpO2, 6+ day battery, Alexa built-in",
        category: "electronics",
        price: 18990,
        brand: "Fitbit",
        rating: 4.5,
        stock: 15,
        image: "https://m.media-amazon.com/images/I/5119d-IDGWL._AC_UF1000,1000_QL80_.jpg"
    },
    {
        id: 107,
        title: "boAt Xtend Smartwatch",
        itemType: "Smart Watch",
        description: "1.69\" square display, stress monitor, 14 sports modes",
        category: "electronics",
        price: 2499,
        brand: "boAt",
        rating: 4.0,
        stock: 55,
        image: "https://cdn.shopify.com/s/files/1/0057/8938/4802/files/pi-001.png?v=1623837573"
    },
    {
        id: 108,
        title: "Garmin Venu Sq",
        itemType: "Smart Watch",
        description: "GPS, health monitoring, 6-day battery, music storage",
        category: "electronics",
        price: 17990,
        brand: "Garmin",
        rating: 4.7,
        stock: 12,
        image: "https://m.media-amazon.com/images/I/71PElcRFwrL._AC_UF1000,1000_QL80_.jpg"
    },
    {
        id: 109,
        title: "OnePlus Watch",
        itemType: "Smart Watch",
        description: "1.39\" AMOLED, SpO2 monitor, 14-day battery life",
        category: "electronics",
        price: 9999,
        brand: "OnePlus",
        rating: 4.3,
        stock: 20,
        image: "https://image01-in.oneplus.net/media/202407/10/b78203e9c64a4a9b3af8caecf56f3e88.png"
    },
    {
        id: 110,
        title: "Huami Amazfit Bip U Pro",
        itemType: "Smart Watch",
        description: "1.43\" display, built-in GPS, 60+ sports modes",
        category: "electronics",
        price: 3999,
        brand: "Amazfit",
        rating: 4.2,
        stock: 35,
        image: "https://in.amazfit.com/cdn/shop/files/1-pro.jpg?v=1691064432&width=1500"
    },
    {
        id: 111,
        title: "Fossil Gen 6",
        itemType: "Smart Watch",
        description: "Wear OS, Snapdragon 4100+, SpO2 tracking",
        category: "electronics",
        price: 19995,
        brand: "Fossil",
        rating: 4.6,
        stock: 8,
        image: "https://imagescdn.thecollective.in/img/app/product/6/664543-6893471.jpg"
    },
    {
        id: 112,
        title: "CrossBeats Ignite S",
        itemType: "Smart Watch",
        description: "1.69\" display, Bluetooth calling, 100+ watch faces",
        category: "electronics",
        price: 1999,
        brand: "CrossBeats",
        rating: 3.9,
        stock: 65,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6Tpts6DzHKudoVTJnbxtS7YO0sW0_z1tApw&s"
    },
    {
        id: 113,
        title: "Titan Smart Pro",
        itemType: "Smart Watch",
        description: "1.78\" AMOLED, Bluetooth calling, 100+ sports modes",
        category: "electronics",
        price: 4995,
        brand: "Titan",
        rating: 4.1,
        stock: 28,
        image: "https://media.croma.com/image/upload/v1675182075/Croma%20Assets/Communication/Wearable%20Devices/Images/248012_6_qrr2rv.png"
    },
    {
        id: 114,
        title: "Honor MagicWatch 2",
        itemType: "Smart Watch",
        description: "1.39\" AMOLED, 2-week battery, 15 workout modes",
        category: "electronics",
        price: 8999,
        brand: "Honor",
        rating: 4.4,
        stock: 18,
        image: "https://m.media-amazon.com/images/I/81TmdO2S6iL.jpg"
    },
    {
        id: 115,
        title: "Micromax IN 2.0",
        itemType: "Smart Watch",
        description: "1.4\" display, SpO2 monitor, 7-day battery life",
        category: "electronics",
        price: 1499,
        brand: "Micromax",
        rating: 3.8,
        stock: 70,
        image: "https://rukminim2.flixcart.com/image/850/1000/jggv53k0/smartwatch/v/y/9/btxy1-black-bastex-original-imaepph3ycxscpjt.jpeg?q=20&crop=false"
    },
    {
        id: 116,
        title: "Oppo Watch Free",
        itemType: "Smart Watch",
        description: "1.64\" AMOLED display, 24/7 heart rate monitoring, 14-day battery life",
        category: "electronics",
        price: 3499,
        brand: "Oppo",
        rating: 4.2,
        stock: 38,
        image: "https://rukminim2.flixcart.com/image/850/1000/l12h1u80/smartwatch/e/8/l/-original-imagcpzes96gnddy.jpeg?q=90&crop=false"
    },

    // earbuds
    {
        id: 201,
        title: "OnePlus Buds Z2",
        itemType: "Wireless Earbuds",
        description: "Active Noise Cancellation, 40hr playback, Dolby Atmos",
        category: "electronics",
        price: 4999,
        brand: "OnePlus",
        rating: 4.3,
        stock: 60,
        image: "https://m.media-amazon.com/images/I/419Pe9doxrL._AC_UF1000,1000_QL80_.jpg"
    },
    {
        id: 202,
        title: "Boat Airdopes 441",
        itemType: "Wireless Earbuds",
        description: "ENx™ Tech, 25hr playback, ASAP™ Charging",
        category: "electronics",
        price: 1299,
        brand: "boAt",
        rating: 4.1,
        stock: 85,
        image: "https://www.boat-lifestyle.com/cdn/shop/products/177292c0-d3d8-4ee3-adfe-7c539f030252_288x.png?v=1625046016"
    },
    {
        id: 203,
        title: "Samsung Galaxy Buds2",
        itemType: "Wireless Earbuds",
        description: "ANC, Lightweight design, 20hr battery",
        category: "electronics",
        price: 8990,
        brand: "Samsung",
        rating: 4.6,
        stock: 30,
        image: "https://m.media-amazon.com/images/I/51X0kXtlBCL.jpg"
    },
    {
        id: 204,
        title: "JBL Tune 230NC",
        itemType: "Wireless Earbuds",
        description: "Active Noise Cancelling, 40hr battery, JBL Pure Bass",
        category: "electronics",
        price: 6999,
        brand: "JBL",
        rating: 4.4,
        stock: 45,
        image: "https://m.media-amazon.com/images/I/61nan8OOchL._AC_UF1000,1000_QL80_DpWeblab_.jpg"
    },
    {
        id: 205,
        title: "Realme Buds Air 3",
        itemType: "Wireless Earbuds",
        description: "ANC, 30hr playback, 10mm Dynamic Bass Driver",
        category: "electronics",
        price: 3499,
        brand: "Realme",
        rating: 4.2,
        stock: 65,
        image: "https://www.unboxify.in/cdn/shop/products/61OVqNnFOuL._SL1500__1_f6d309fb-9e70-45a3-a5b5-f978cb9869ec.jpg?v=1694963316"
    },
    {
        id: 206,
        title: "Apple AirPods Pro (2nd Gen)",
        itemType: "Wireless Earbuds",
        description: "Active Noise Cancellation, Spatial Audio, 30hr battery",
        category: "electronics",
        price: 24900,
        brand: "Apple",
        rating: 4.8,
        stock: 25,
        image: "https://m.media-amazon.com/images/I/61SUj2aKoEL._SL1500_.jpg"
    },
    {
        id: 207,
        title: "Noise Buds VS104",
        itemType: "Wireless Earbuds",
        description: "Quad Mic ENC, 50hr playback, Instacharge",
        category: "electronics",
        price: 1799,
        brand: "Noise",
        rating: 4.0,
        stock: 70,
        image: "https://m.media-amazon.com/images/I/51HBom8xz7L._SL1200_.jpg"
    },
    {
        id: 208,
        title: "Oppo Enco X2",
        itemType: "Wireless Earbuds",
        description: "Co-created with Dynaudio, ANC, 40hr battery",
        category: "electronics",
        price: 9999,
        brand: "Oppo",
        rating: 4.5,
        stock: 35,
        image: "https://www.oppo.com/content/dam/oppo/common/mkt/v2-2/enco-x2/navigation/navigation_427x600_black.png"
    },
    {
        id: 209,
        title: "Boult Audio ProBass",
        itemType: "Wireless Earbuds",
        description: "Zen ENC, 40hr playback, IPX5 Waterproof",
        category: "electronics",
        price: 1499,
        brand: "Boult Audio",
        rating: 4.1,
        stock: 80,
        image: "https://rukminim2.flixcart.com/image/850/1000/xif0q/headphone/m/a/5/-original-imagg33vvpyve8uq.jpeg?q=20&crop=false"
    },
    {
        id: 210,
        title: "pTron Bassbuds Pro",
        itemType: "Wireless Earbuds",
        description: "Deep Bass, 20hr playback, Touch Control",
        category: "electronics",
        price: 999,
        brand: "pTron",
        rating: 3.9,
        stock: 90,
        image: "https://ptron.in/cdn/shop/products/Mainimage4000x4000_b7d5664b-a047-4606-8460-b15627f2f845.png?v=1613132527"
    },
    {
        id: 211,
        title: "Sony WF-C500",
        itemType: "Wireless Earbuds",
        description: "20hr battery, DSEE, IPX4 Waterproof",
        category: "electronics",
        price: 5490,
        brand: "Sony",
        rating: 4.3,
        stock: 40,
        image: "https://www.sony.co.in/image/6ff70f66ce935f02861635b3e936a70c?fmt=pjpeg&wid=330&bgcolor=FFFFFF&bgc=FFFFFF"
    },
    {
        id: 212,
        title: "Mivi DuoPods A25",
        itemType: "Wireless Earbuds",
        description: "Quad Mics, 50hr playback, Low Latency Mode",
        category: "electronics",
        price: 1499,
        brand: "Mivi",
        rating: 4.0,
        stock: 75,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT-Q5Th-z44UbnGRuudUDe4-M-SqFGr7zvwCw&s"
    },
    {
        id: 213,
        title: "CrossBeats Orbit",
        itemType: "Wireless Earbuds",
        description: "40hr battery, ENC, IPX5 Waterproof",
        category: "electronics",
        price: 1999,
        brand: "CrossBeats",
        rating: 1.4,
        stock: 60,
        image: "https://crossbeats.com/cdn/shop/files/Black01_99ca2394-efee-45e7-bb1f-51ec04f203f8.png?crop=center&height=1200&v=1728899396&width=1200"
    },
    {
        id: 214,
        title: "Jabra Elite 3",
        itemType: "Wireless Earbuds",
        description: "Customizable EQ, 28hr battery, IP55 Waterproof",
        category: "electronics",
        price: 5999,
        brand: "Jabra",
        rating: 4.4,
        stock: 30,
        image: "https://media.croma.com/image/upload/v1674048604/Croma%20Assets/Communication/Headphones%20and%20Earphones/Images/244433_0_v8bqsx.png"
    },
    {
        id: 215,
        title: "Skullcandy Dime 2",
        itemType: "Wireless Earbuds",
        description: "12hr battery, Tile Finding, IPX4 Waterproof",
        category: "electronics",
        price: 1999,
        brand: "Skullcandy",
        rating: 2.2,
        stock: 65,
        image: "https://m.media-amazon.com/images/I/61KY-QEhTCL._AC_UF1000,1000_QL80_.jpg"
    },
    {
        id: 216,
        title: "Nothing Ear (1)",
        itemType: "Wireless Earbuds",
        description: "ANC, 34hr battery, Unique transparent design",
        category: "electronics",
        price: 7999,
        brand: "Nothing",
        rating: 4.2,
        stock: 45,
        image: "https://cdn.shopify.com/s/files/1/0514/8554/0505/files/D00.png?v=1646036207"
    },
    {
        id: 217,
        title: "Mi True Wireless Earbuds 3 Pro",
        itemType: "Wireless Earbuds",
        description: "Dual drivers, ANC, 27hr battery",
        category: "electronics",
        price: 5999,
        brand: "Xiaomi",
        rating: 3.1,
        stock: 50,
        image: "https://i01.appmifile.com/webfile/globalimg/products/new/redmi-buds-3-pro/m_overview_02s.jpg"
    },

    // kids
    {
        id: 302,
        title: "Colorful Backpack",
        itemType: "Backpack",
        description: "Durable school backpack with multiple compartments",
        category: "fashion",
        price: 599,
        brand: "Wildcraft",
        rating: 4.5,
        stock: 120,
        image: "https://kidspark.co.in/cdn/shop/files/73copy.jpg?v=1735551058",
        gender: "kids"
    },
    {
        id: 303,
        title: "Cartoon T-Shirt",
        itemType: "T-Shirt",
        description: "Cotton t-shirt with favorite cartoon characters",
        category: "fashion",
        price: 299,
        brand: "Disney",
        rating: 4.7,
        stock: 200,
        image: "https://primethread.in/wp-content/uploads/2022/04/Cartoon-tom-T-shirt.webp",
        gender: "kids"
    },
    {
        id: 304,
        title: "Sports Shoes",
        itemType: "Shoes",
        description: "Lightweight running shoes for active kids",
        category: "fashion",
        price: 1299,
        brand: "Nike Kids",
        rating: 4.8,
        stock: 85,
        image: "https://images.meesho.com/images/products/429457678/y77pq_512.webp",
        gender: "kids"
    },
    {
        id: 305,
        title: "Denim Jeans",
        itemType: "Jeans",
        description: "Comfortable stretchable denim for all-day wear",
        category: "fashion",
        price: 799,
        brand: "Lee",
        rating: 4.3,
        stock: 150,
        image: "https://images.meesho.com/images/products/448755660/6c2s9_512.webp",
        gender: "kids"
    },
    {
        id: 306,
        title: "Winter Jacket",
        itemType: "Jacket",
        description: "Warm padded jacket for cold weather",
        category: "fashion",
        price: 1499,
        brand: "Puma",
        rating: 4.6,
        stock: 60,
        image: "https://m.media-amazon.com/images/I/81X28gmsFBL._AC_UY1100_.jpg",
        gender: "kids"
    },
    {
        id: 307,
        title: "Baseball Cap",
        itemType: "Cap",
        description: "Adjustable cap with cool prints",
        category: "fashion",
        price: 349,
        brand: "Adidas",
        rating: 4.2,
        stock: 180,
        image: "https://images-cdn.ubuy.co.in/633f0473045adc449b7a85e7-nickelodeon-boys-paw-patrol-baseball.jpg",
        gender: "kids"
    },
    {
        id: 308,
        title: "Cotton Socks Pack",
        itemType: "Socks",
        description: "Pack of 5 colorful ankle socks",
        category: "fashion",
        price: 199,
        brand: "H&M",
        rating: 4.4,
        stock: 300,
        image: "https://m.media-amazon.com/images/I/71b37i72jhL._AC_UY1100_.jpg",
        gender: "kids"
    },
    {
        id: 309,
        title: "Unicorn Backpack",
        itemType: "Backpack",
        description: "Cute unicorn-themed backpack for little ones",
        category: "fashion",
        price: 499,
        brand: "Skybags",
        rating: 4.8,
        stock: 90,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_upchzEgABW2fJkvAqdtMqoKJFYyDIdNuOA&s",
        gender: "kids"
    },
    {
        id: 310,
        title: "Superhero T-Shirt",
        itemType: "T-Shirt",
        description: "Official superhero merchandise t-shirt",
        category: "fashion",
        price: 399,
        brand: "Marvel",
        rating: 4.9,
        stock: 170,
        image: "https://m.media-amazon.com/images/I/71tstLVgcgL._AC_UY1100_.jpg",
        gender: "kids"
    },
    {
        id: 311,
        title: "School Shoes",
        itemType: "Shoes",
        description: "Formal black shoes for school uniform",
        category: "fashion",
        price: 899,
        brand: "Bata",
        rating: 4.5,
        stock: 110,
        image: "https://images.meesho.com/images/products/458591083/xpwct_512.webp",
        gender: "kids"
    },
    {
        id: 312,
        title: "Cargo Pants",
        itemType: "Jeans",
        description: "Stylish cargo pants with multiple pockets",
        category: "fashion",
        price: 699,
        brand: "US Polo",
        rating: 4.3,
        stock: 130,
        image: "https://images-cdn.ubuy.co.in/657b0f402527684f37169038-patpat-boys-cargo-pants-with-pocket.jpg",
        gender: "kids"
    },
    {
        id: 313,
        title: "Rain Jacket",
        itemType: "Jacket",
        description: "Waterproof jacket with hood for rainy days",
        category: "fashion",
        price: 999,
        brand: "Columbia",
        rating: 4.7,
        stock: 75,
        image: "https://assets.myntassets.com/w_412,q_60,dpr_2,fl_progressive/assets/images/23034472/2023/5/6/574da54c-4d9f-47d4-ad5c-9c1ede37b9261683346456612RainJacket1.jpg",
        gender: "kids"
    },
    {
        id: 314,
        title: "Bucket Hat",
        itemType: "Cap",
        description: "Sun protection bucket hat for outdoor activities",
        category: "fashion",
        price: 449,
        brand: "GAP",
        rating: 4.1,
        stock: 95,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQM3ZyneUfPuHD1rtCCQuinkzHjWXpvR8x5Wg&s",
        gender: "kids"
    },
    {
        id: 315,
        title: "Character Socks",
        itemType: "Socks",
        description: "Pack of 3 socks with cartoon characters",
        category: "fashion",
        price: 249,
        brand: "Disney",
        rating: 4.6,
        stock: 220,
        image: "https://m.media-amazon.com/images/I/61sUuR8p3JL._AC_UY1100_.jpg",
        gender: "kids"
    },
    {
        id: 316,
        title: "Lunch Bag Combo",
        itemType: "Backpack",
        description: "Matching backpack and lunch bag set",
        category: "fashion",
        price: 799,
        brand: "Paw Patrol",
        rating: 4.7,
        stock: 65,
        image: "https://www.kuviba.com/cdn/shop/files/WhatsAppImage2024-04-13at17.30.13.jpg?v=1713013521",
        gender: "kids"
    },
    {
        id: 317,
        title: "Graphic T-Shirt",
        itemType: "T-Shirt",
        description: "Funny graphic print cotton t-shirt",
        category: "fashion",
        price: 349,
        brand: "Gini & Jony",
        rating: 4.4,
        stock: 190,
        image: "https://assets.ajio.com/medias/sys_master/root/20250512/fJmh/682226837a6cd4182f2993ff/-473Wx593H-700232188-multi-MODEL.jpg",
        gender: "kids"
    },
    {
        id: 318,
        title: "Sandals",
        itemType: "Shoes",
        description: "Comfortable summer sandals with adjustable straps",
        category: "fashion",
        price: 599,
        brand: "Crocs",
        rating: 4.6,
        stock: 140,
        image: "https://staranddaisy.in/wp-content/uploads/2024/02/jh1438-main-2-copy-0.jpg",
        gender: "kids"
    },
    {
        id: 319,
        title: "Jogger Pants",
        itemType: "Jeans",
        description: "Soft jogger pants with elastic waistband",
        category: "fashion",
        price: 649,
        brand: "Allen Solly",
        rating: 4.5,
        stock: 160,
        image: "https://5.imimg.com/data5/SELLER/Default/2024/6/424696424/JS/BW/JB/223561816/whatsapp-image-2024-06-04-at-11-11-06-pm-500x500.jpeg",
        gender: "kids"
    },
    {
        id: 320,
        title: "Puffer Jacket",
        itemType: "Jacket",
        description: "Lightweight puffer jacket for winter",
        category: "fashion",
        price: 1199,
        brand: "The North Face",
        rating: 4.8,
        stock: 50,
        image: "https://m.media-amazon.com/images/I/617tCg0euFL._AC_UY1100_.jpg",
        gender: "kids"
    },
    {
        id: 321,
        title: "Sun Visor",
        itemType: "Cap",
        description: "Breathable sun visor for summer protection",
        category: "fashion",
        price: 299,
        brand: "Under Armour",
        rating: 4.0,
        stock: 110,
        image: "https://m.media-amazon.com/images/I/61fPlhlsS+L._AC_UF894,1000_QL80_.jpg",
        gender: "kids"
    },

    // appliances
    {
        id: 401,
        title: "Inverter Split AC",
        itemType: "Air Conditioner",
        description: "1.5 Ton 5-star inverter split AC with PM 2.5 filter",
        category: "appliances",
        price: 42990,
        brand: "LG",
        rating: 4.5,
        stock: 35,
        image: "https://www.lg.com/content/dam/channel/wcms/in/images/split-ac/gallery/updated-1-2-gallery/US-Q19BNZE-2010x1334-1.jpg/_jcr_content/renditions/thum-1600x1062.jpeg"
    },
    {
        id: 402,
        title: "Frost-Free Refrigerator",
        itemType: "Refrigerator",
        description: "260L 3-star frost-free refrigerator with stabilizer-free operation",
        category: "appliances",
        price: 28990,
        brand: "Samsung",
        rating: 4.4,
        stock: 42,
        image: "https://www.jiomart.com/images/product/original/493692179/samsung-236-litre-2-star-frost-free-double-door-refrigerator-camellia-blue-rt28c3122cu-hl-digital-o493692179-p600107107-1-202304031317.jpeg?im=Resize=(420,420)"
    },
    {
        id: 403,
        title: "Semi-Automatic Washing Machine",
        itemType: "Washing Machine",
        description: "7.2 kg semi-automatic top load washing machine",
        category: "appliances",
        price: 12990,
        brand: "Whirlpool",
        rating: 4.2,
        stock: 58,
        image: "https://media.croma.com/image/upload/v1722257794/Croma%20Assets/Large%20Appliances/Washers%20and%20Dryers/Images/300475_0_kaffyj.png"
    },
    {
        id: 404,
        title: "Convection Microwave",
        itemType: "Microwave",
        description: "28L convection microwave with 101 auto cook menus",
        category: "appliances",
        price: 16990,
        brand: "IFB",
        rating: 4.6,
        stock: 27,
        image: "https://rukminim2.flixcart.com/image/750/900/xif0q/microwave-new/n/n/i/-original-imagk3hjy9kveyzw.jpeg?q=90&crop=false"
    },
    {
        id: 405,
        title: "Air Purifier",
        itemType: "Air Purifier",
        description: "True HEPA filter with PM 2.5 and VOC sensor",
        category: "appliances",
        price: 14999,
        brand: "Dyson",
        rating: 4.7,
        stock: 19,
        image: "https://jsbhealthcare.co.in/cdn/shop/files/Air_Purifier_for_Home_Room_JSB_HF123.jpg?v=1742103520"
    },
    {
        id: 406,
        title: "Robot Vacuum Cleaner",
        itemType: "Vacuum Cleaner",
        description: "Smart robot vacuum with LiDAR navigation and app control",
        category: "appliances",
        price: 32990,
        brand: "Eureka Forbes",
        rating: 4.3,
        stock: 14,
        image: "https://jamesandco.in/wp-content/uploads/2024/09/61Vt8i4F8gL._SL1500.jpg"
    },
    {
        id: 407,
        title: "Induction Cooktop",
        itemType: "Cooktop",
        description: "2100W induction cooktop with 10 power levels",
        category: "appliances",
        price: 2990,
        brand: "Prestige",
        rating: 4.1,
        stock: 76,
        image: "https://www.realsimple.com/thmb/8Rh-TflizO2DYDKDQ9SadSr0IbE=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Induction-Cooktop-GettyImages-1550758299-662f98618b154c4cb2e0d2dd73ad5872.jpg"
    },
    {
        id: 408,
        title: "Food Processor",
        itemType: "Food Processor",
        description: "1000W food processor with 10 attachments",
        category: "appliances",
        price: 8990,
        brand: "Morphy Richards",
        rating: 4.4,
        stock: 31,
        image: "https://images-cdn.ubuy.co.in/64adfb56bb1884560e58623b-kitchenaid-13-cup-food-processor.jpg"
    },
    {
        id: 409,
        title: "Water Purifier",
        itemType: "Water Purifier",
        description: "RO+UV+UF purification with 8L storage tank",
        category: "appliances",
        price: 18990,
        brand: "Kent",
        rating: 4.5,
        stock: 23,
        image: "https://havells.com/media/catalog/product/cache/844a913d283fe95e56e39582c5f2767b/g/h/ghwraqd015.jpg"
    },
    {
        id: 410,
        title: "Inverter Air Cooler",
        itemType: "Air Cooler",
        description: "55L desert air cooler with inverter technology",
        category: "appliances",
        price: 15990,
        brand: "Symphony",
        rating: 4.0,
        stock: 38,
        image: "https://m.media-amazon.com/images/I/51jRT2cpVBL._AC_UF1000,1000_QL80_.jpg"
    },
    {
        id: 411,
        title: "Window AC",
        itemType: "Air Conditioner",
        description: "1.5 Ton 3-star window AC with eco mode",
        category: "appliances",
        price: 32990,
        brand: "Voltas",
        rating: 4.2,
        stock: 29,
        image: "https://kaydeeelectronics.in/cdn/shop/files/untitled-design-2024-07-25t130030550-66a1ff2fe8b40.webp?v=1721892680&width=1946"
    },
    {
        id: 412,
        title: "Side-by-Side Refrigerator",
        itemType: "Refrigerator",
        description: "655L smart convertible refrigerator with twin cooling",
        category: "appliances",
        price: 125990,
        brand: "Samsung",
        rating: 4.7,
        stock: 8,
        image: "https://d1pjg4o0tbonat.cloudfront.net/content/dam/midea-aem/in/refrigerators/sbs-refrigerators/midea-482-l-side-by-side-refrigerator-with-inverter-(mdrs619fgg28ind,-black-jazz)/REF%20SBS%20482L%20IN2.png/jcr:content/renditions/cq5dam.compression.png"
    },
    {
        id: 413,
        title: "Fully Automatic Washing Machine",
        itemType: "Washing Machine",
        description: "8 kg fully automatic front load with steam wash",
        category: "appliances",
        price: 37990,
        brand: "LG",
        rating: 4.6,
        stock: 21,
        image: "https://www.jiomart.com/images/product/original/493692416/lg-10-kg-front-load-fully-automatic-washing-machine-fhp1410z5m-middle-black-digital-o493692416-p599326155-0-202303142011.jpeg?im=Resize=(420,420)"
    },
    {
        id: 414,
        title: "Grill Microwave",
        itemType: "Microwave",
        description: "32L grill microwave with smart sensor cooking",
        category: "appliances",
        price: 13990,
        brand: "Samsung",
        rating: 4.3,
        stock: 34,
        image: "https://5.imimg.com/data5/SELLER/Default/2023/1/TA/HD/SM/182750136/grill-microwave-oven.jpg"
    },
    {
        id: 415,
        title: "Air Purifier with Humidifier",
        itemType: "Air Purifier",
        description: "2-in-1 air purifier with humidifier and smart sensors",
        category: "appliances",
        price: 24999,
        brand: "Philips",
        rating: 4.5,
        stock: 16,
        image: "https://triptisales.in/wp-content/uploads/2024/06/Difference-between-air-purifiers-and-humidifiers.png"
    },
    {
        id: 416,
        title: "Handheld Vacuum Cleaner",
        itemType: "Vacuum Cleaner",
        description: "Cordless handheld vacuum with 30min runtime",
        category: "appliances",
        price: 8990,
        brand: "Mi",
        rating: 4.2,
        stock: 47,
        image: "https://m.media-amazon.com/images/I/61nsOzbC4BL._UF894,1000_QL80_.jpg"
    },
    {
        id: 417,
        title: "Gas Cooktop",
        itemType: "Cooktop",
        description: "3 burner gas cooktop with auto ignition",
        category: "appliances",
        price: 5990,
        brand: "Sunflame",
        rating: 4.0,
        stock: 63,
        image: "https://www.rasoishop.com/cdn/shop/files/8901365403708-7_3.png?v=1713769793"
    },
    {
        id: 418,
        title: "Juicer Mixer Grinder",
        itemType: "Food Processor",
        description: "750W juicer mixer grinder with 3 jars",
        category: "appliances",
        price: 3490,
        brand: "Bajaj",
        rating: 4.3,
        stock: 82,
        image: "https://m.media-amazon.com/images/I/71vfrhmJ1SL.jpg"
    },
    {
        id: 419,
        title: "UV Water Purifier",
        itemType: "Water Purifier",
        description: "UV purification with 7-stage filtration",
        category: "appliances",
        price: 12990,
        brand: "Aquaguard",
        rating: 4.4,
        stock: 37,
        image: "https://m.media-amazon.com/images/I/71QrJjnSxFL.jpg"
    },
    {
        id: 420,
        title: "Tower Air Cooler",
        itemType: "Air Cooler",
        description: "45L tower air cooler with 4-way air deflection",
        category: "appliances",
        price: 11990,
        brand: "Honeywell",
        rating: 4.1,
        stock: 45,
        image: "https://cdn.accentuate.io/605785456944/-1695035269432/3-(1)-v1701346119711.png?800x800"
    },


    // bannerItem
    {
        id: 1001,
        title: "Samsung S25 Ultra",
        itemType: "Smartphone",
        description: "Samsung Galaxy S25 Ultra with 6.9\" AMOLED display, Snapdragon 8 Gen 3, 200MP quad camera, and 5000mAh battery",
        category: "smartphones",
        price: 129999,
        brand: "Samsung",
        rating: 4.8,
        stock: 35,
        bannerImage: "https://rukminim2.flixcart.com/fk-p-flap/1620/270/image/9c1432bb6c9f5476.jpeg?q=80",
        image: 'https://images.samsung.com/in/smartphones/galaxy-s25-ultra/buy/product_color_gray_MO.png?imbypass=true',
        advertisement: true
    },
    {
        id: 1002,
        title: "Xiaomi X Series 43\" 4K Ultra HD Smart TV",
        itemType: "Smart TV",
        description: "Xiaomi X Series 108cm (43 inch) 4K Ultra HD Smart LED TV with Dolby Audio, PatchWall, Google TV, and Vivid Picture Engine",
        category: "electronics",
        price: 26999,
        brand: "Xiaomi",
        rating: 4.5,
        stock: 40,
        bannerImage: "https://www.bajajmall.in/content/dam/emistoremarketplace/index/05-03-25/4/mibp/bb/MIBP_Bigbanner_2_Desk_xiaomixseries108cm43inch4kultrahdsmarttvblackxiaomix43gtv20244357663_PDP_B2B.jpg",
        image: 'https://img-prd-pim.poorvika.com/product/xiaomi-led-smart-tv-x-series-2024-4k-ultra-hd-43-inch-front-view.png',
        advertisement: true
    },
    {
        id: 1003,
        title: "HP Victus Gaming Laptop",
        itemType: "Laptop",
        description: "HP Victus with 16.1\" FHD 144Hz display, AMD Ryzen 7 7840HS, 16GB RAM, 1TB SSD, RTX 4060 8GB Graphics, and Windows 11 Home",
        category: "laptops",
        price: 55990,
        brand: "HP",
        rating: 4.6,
        stock: 15,
        bannerImage: "https://rukminim1.flixcart.com/fk-p-flap/1620/270/image/91193de348290c73.jpeg?q=80",
        image: "https://m.media-amazon.com/images/I/71oAs8eJk-L.jpg",
        advertisement: true
    },
    // {
    //     id: 16,
    //     title: "Asus VivoBook 14",
    //     itemType: "Laptop",
    //     description: "14-inch FHD laptop with Intel Core i3 and fingerprint sensor",
    //     category: "laptops",
    //     price: 39999,
    //     brand: "Asus",
    //     rating: 4.2,
    //     stock: 22,
    //     image: "https://dlcdnwebimgs.asus.com/files/media/71311dd4-7d8a-4b2a-a48e-91b24f456f7c/v3/features/images/large/1x/s4/main.jpg"
    // },




];

export const setLocalStorage = () => {
    localStorage.setItem('productData', JSON.stringify(products))

}
export const getLocalStorage = () => {
    const productData = JSON.parse(localStorage.getItem('productData'));
    return productData;
}